name: 'Documentation MapReduce'

on:
  push:
    branches:
      - project
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          doxyfile-path: ./Doxyfile
          working-directory: '.'
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages

  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Get boost 1.81
        working-directory: '.'
        run: ls && pwd && wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz && tar xvf boost_1_81_0.tar.gz
      
      - name: Build boost 1.81
        working-directory: './boost_1_81_0'
        run: ls && pwd && ./bootstrap.sh --prefix=/usr/ && sudo ./b2 install && echo "-----------------------"

      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt-get update -y && sudo apt-get install cmake libssl-dev libwolfssl-dev zlib1g-dev -y
